language: node_js

sudo: false

notifications:
  email:
  - guowei@shnow.cn

node_js:
 - 5
 - 5.1
 - node

script:
  - npm test
  - npm run cover
  # - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls
  # 本地可以成功运行，到了自动集成却不行了。。。我去。。。